#### 🧠 Pandas Case Study: Online Retail Orders

In [ ]:
## ✅ Step 1: Create Dataset

In [2]:
import pandas as pd

data = {
    "OrderID": range(1001, 1021),
    "OrderDate": [
        "2024-01-01","2024-01-02","2024-01-03","2024-01-04","2024-01-05",
        "2024-01-06","2024-01-07","2024-01-08","2024-01-09","2024-01-10",
        "2024-01-11","2024-01-12","2024-01-13","2024-01-14","2024-01-15",
        "2024-01-16","2024-01-17","2024-01-18","2024-01-19","2024-01-20"
    ],
    "Customer": ["Amit","Neha","Rahul","Sneha","Vikram","Amit","Neha","Rohit","Pooja","Amit",
                 "Riya","Rahul","Sneha","Vikram","Amit","Rohit","Pooja","Neha","Riya","Rahul"],
    "City": ["Pune","Mumbai","Delhi","Pune","Bangalore","Pune","Mumbai","Delhi","Pune","Pune",
             "Mumbai","Delhi","Pune","Bangalore","Pune","Delhi","Pune","Mumbai","Mumbai","Delhi"],
    "Category": ["Electronics","Clothing","Electronics","Groceries","Clothing","Electronics",
                 "Groceries","Clothing","Electronics","Groceries","Clothing","Electronics",
                 "Groceries","Clothing","Electronics","Groceries","Electronics","Clothing",
                 "Electronics","Groceries"],
    "Product": ["Laptop","T-Shirt","Mobile","Rice Bag","Jeans","Headphones","Oil","Shirt",
                "Tablet","Milk","Jacket","Camera","Wheat","Trousers","Speaker","Sugar",
                "Smartwatch","Dress","Powerbank","Tea"],
    "Quantity": [1,3,1,5,2,2,3,2,1,4,1,1,6,2,1,3,1,2,2,5],
    "Price": [55000,800,20000,1200,1500,2500,900,1000,15000,600,2200,30000,1800,1700,4000,700,8000,1400,1200,500],
    "Discount": [5000,0,2000,100,0,200,50,0,1500,0,100,3000,200,0,500,0,1000,100,0,50],
    "Rating": [5,4,5,3,4,4,3,4,5,3,4,5,3,4,5,3,5,4,4,3],
    "PaymentMethod": ["UPI","COD","Card","UPI","Card","UPI","COD","Card","UPI","UPI",
                      "Card","Card","COD","UPI","UPI","COD","Card","UPI","Card","COD"]
}

df = pd.DataFrame(data)
df["OrderDate"] = pd.to_datetime(df["OrderDate"])

df.head()

,OrderID,OrderDate,Customer,City,Category,Product,Quantity,Price,Discount,Rating,PaymentMethod
0,1001,2024-01-01,Amit,Pune,Electronics,Laptop,1,55000,5000,5,UPI
1,1002,2024-01-02,Neha,Mumbai,Clothing,T-Shirt,3,800,0,4,COD
2,1003,2024-01-03,Rahul,Delhi,Electronics,Mobile,1,20000,2000,5,Card
3,1004,2024-01-04,Sneha,Pune,Groceries,Rice Bag,5,1200,100,3,UPI
4,1005,2024-01-05,Vikram,Bangalore,Clothing,Jeans,2,1500,0,4,Card

#### 🎯 SECTION 1 — Basic Exploration

In [3]:
### Q1. Total number of orders
len(df)
#df.shape[0]

20

In [4]:
### Q2. Total revenue (before discount)
#(df["Price"]* df["Quantity"]).sum()
(df["Price"] * df["Quantity"]).sum()

np.int64(181700)

In [6]:
### Q3. Total discount given
(df["Discount"] * df["Quantity"]).sum()

np.int64(15800)

In [7]:
### Q4. Net revenue after discount
((df["Price"] - df["Discount"]) * df["Quantity"]).sum()

np.int64(165900)

In [8]:
### Q5. Average order value
net_revenue = ((df["Price"] - df["Discount"]) * df["Quantity"]).sum()
avg_order_value = net_revenue / len(df)
avg_order_value

np.float64(8295.0)

#### 🎯 SECTION 2 — Customer Insights

In [9]:
df.head(1)

,OrderID,OrderDate,Customer,City,Category,Product,Quantity,Price,Discount,Rating,PaymentMethod
0,1001,2024-01-01,Amit,Pune,Electronics,Laptop,1,55000,5000,5,UPI

In [10]:
### Q6. Top 5 customers by spending

df["NetAmount"] = (df["Price"] - df["Discount"]) * df["Quantity"]

df.groupby("Customer")["NetAmount"].sum() \
  .sort_values(ascending=False) \
  .head(5)

Customer
Amit     60500
Rahul    47250
Pooja    20500
Sneha    15100
Neha      7550
Name: NetAmount, dtype: int64

In [11]:
df.columns

Index(['OrderID', 'OrderDate', 'Customer', 'City', 'Category', 'Product',
       'Quantity', 'Price', 'Discount', 'Rating', 'PaymentMethod',
       'NetAmount'],
      dtype='object')

In [12]:
### Q7. Customer who placed most orders
# Method 1 
df["Customer"].value_counts().idxmax()

# Customer with most orders
df["Customer"].value_counts().idxmax()
# method using groupby
df.groupby("Customer").size().sort_values(ascending=False).head(1)

Customer
Amit    4
dtype: int64

In [13]:
### Q8. Average rating per customer
df.groupby("Customer")["Rating"].mean()

Customer
Amit      4.250000
Neha      3.666667
Pooja     5.000000
Rahul     4.333333
Riya      4.000000
Rohit     3.500000
Sneha     3.000000
Vikram    4.000000
Name: Rating, dtype: float64

In [14]:
### Q9. Customer lifetime value (CLV)
df["NetAmount"] = (df["Price"] - df["Discount"]) * df["Quantity"]

df.groupby("Customer")["NetAmount"].sum().sort_values(ascending=False)

Customer
Amit      60500
Rahul     47250
Pooja     20500
Sneha     15100
Neha       7550
Vikram     6400
Riya       4500
Rohit      4100
Name: NetAmount, dtype: int64

#### 🎯 SECTION 3 — City Analysis

In [15]:
### Q10. Orders per city
#df["City"].value_counts()
df.groupby("City")["OrderID"].count()

City
Bangalore    2
Delhi        5
Mumbai       5
Pune         8
Name: OrderID, dtype: int64

In [16]:
df.head(2)

,OrderID,OrderDate,Customer,City,Category,Product,Quantity,Price,Discount,Rating,PaymentMethod,NetAmount
0,1001,2024-01-01,Amit,Pune,Electronics,Laptop,1,55000,5000,5,UPI,50000
1,1002,2024-01-02,Neha,Mumbai,Clothing,T-Shirt,3,800,0,4,COD,2400

In [17]:
### Q11. Revenue per city
df.groupby("City")["NetAmount"].sum()

City
Bangalore     6400
Delhi        51350
Mumbai       12050
Pune         96100
Name: NetAmount, dtype: int64

In [18]:
### Q12. Most profitable city
df.groupby("City")["NetAmount"].sum().sort_values(ascending=False).head(1)

City
Pune    96100
Name: NetAmount, dtype: int64

In [19]:
### Q13. City with highest average order value
df.groupby("City")["NetAmount"].mean().sort_values(ascending=False).head(1)

City
Pune    12012.5
Name: NetAmount, dtype: float64

#### 🎯 SECTION 4 — Product & Category Insights

In [20]:
### Q14. Most popular category
df["Category"].value_counts().idxmax()

'Electronics'

In [22]:
### Q15. Category generating highest revenue
df.groupby("Category")["NetAmount"].sum().sort_values(ascending=False)

Category
Electronics    126000
Groceries       24400
Clothing        15500
Name: NetAmount, dtype: int64

In [24]:
### Q16. Most ordered product
df.groupby("Product")["Quantity"].sum().sort_values(ascending=False).head(1)

Product
Wheat    6
Name: Quantity, dtype: int64

In [25]:
### Q17. Highest revenue product
df.groupby("Product")["NetAmount"].sum().sort_values(ascending=False).head(1)

Product
Laptop    50000
Name: NetAmount, dtype: int64

In [26]:
### Q18. Average rating by category
df.groupby("Category")["Rating"].mean().sort_values(ascending=False)

Category
Electronics    4.75
Clothing       4.00
Groceries      3.00
Name: Rating, dtype: float64

#### 🎯 SECTION 5 — Time Analysis

In [27]:
### Q19. Orders per day
df["Date"] = pd.to_datetime(df["OrderDate"])

df.groupby(df["Date"].dt.date)["OrderID"].count()

Date
2024-01-01    1
2024-01-02    1
2024-01-03    1
2024-01-04    1
2024-01-05    1
2024-01-06    1
2024-01-07    1
2024-01-08    1
2024-01-09    1
2024-01-10    1
2024-01-11    1
2024-01-12    1
2024-01-13    1
2024-01-14    1
2024-01-15    1
2024-01-16    1
2024-01-17    1
2024-01-18    1
2024-01-19    1
2024-01-20    1
Name: OrderID, dtype: int64

In [28]:
### Q20. Day with highest sales
df["OrderDate"] = pd.to_datetime(df["OrderDate"])

df.groupby(df["OrderDate"].dt.date)["NetAmount"].sum().idxmax()

datetime.date(2024, 1, 1)

In [30]:
### Q21. Weekend vs weekday revenue
df["DayType"] = df["OrderDate"].dt.dayofweek.apply(
    lambda x: "Weekend" if x >= 5 else "Weekday"
)
df.groupby("DayType")["NetAmount"].sum()

DayType
Weekday    143500
Weekend     22400
Name: NetAmount, dtype: int64

In [31]:
### Q22. Rolling 3-day average sales
df["OrderDate"] = pd.to_datetime(df["OrderDate"])
daily_sales = df.groupby(df["OrderDate"].dt.date)["NetAmount"].sum()
rolling_avg = daily_sales.rolling(window=3).mean()

rolling_avg

OrderDate
2024-01-01             NaN
2024-01-02             NaN
2024-01-03    23466.666667
2024-01-04     8633.333333
2024-01-05     8833.333333
2024-01-06     4366.666667
2024-01-07     3383.333333
2024-01-08     3050.000000
2024-01-09     6016.666667
2024-01-10     5966.666667
2024-01-11     6000.000000
2024-01-12    10500.000000
2024-01-13    12900.000000
2024-01-14    13333.333333
2024-01-15     5500.000000
2024-01-16     3000.000000
2024-01-17     4200.000000
2024-01-18     3900.000000
2024-01-19     4000.000000
2024-01-20     2416.666667
Name: NetAmount, dtype: float64

#### 🎯 SECTION 6 — Discount Analysis

In [32]:
### Q23. Orders with discount vs without
df["DiscountFlag"] = df["Discount"].apply(
    lambda x: "With Discount" if x > 0 else "No Discount"
)

df["DiscountFlag"].value_counts()

DiscountFlag
With Discount    13
No Discount       7
Name: count, dtype: int64

In [33]:
### Q24. Does discount increase quantity ordered?
df["DiscountFlag"] = df["Discount"].apply(
    lambda x: "With Discount" if x > 0 else "No Discount"
)
df.groupby("DiscountFlag")["Quantity"].mean()

DiscountFlag
No Discount      2.571429
With Discount    2.307692
Name: Quantity, dtype: float64

In [34]:
### Q25. Avg discount per category
df.groupby("Category")["Discount"].mean()

Category
Clothing         33.333333
Electronics    1650.000000
Groceries        66.666667
Name: Discount, dtype: float64

In [35]:
### Q26. Discount impact on ratings
df.groupby(df["Discount"] > 0)["Rating"].mean()

Discount
False    3.714286
True     4.153846
Name: Rating, dtype: float64

#### 🎯 SECTION 7 — Advanced Pandas Skills

In [36]:
### Q27. Create column: `NetPrice = Price - Discount`

df["NetPrice"] = df["Price"] - df["Discount"]

In [38]:
### Q28. Create column: `TotalValue = Quantity * NetPrice`
df["TotalValue"] = df["Quantity"] * df["NetPrice"]
df

,OrderID,OrderDate,Customer,City,Category,Product,Quantity,Price,Discount,Rating,PaymentMethod,NetAmount,Date,DayType,DiscountFlag,NetPrice,TotalValue
0,1001,2024-01-01,Amit,Pune,Electronics,Laptop,1,55000,5000,5,UPI,50000,2024-01-01,Weekday,With Discount,50000,50000
1,1002,2024-01-02,Neha,Mumbai,Clothing,T-Shirt,3,800,0,4,COD,2400,2024-01-02,Weekday,No Discount,800,2400
2,1003,2024-01-03,Rahul,Delhi,Electronics,Mobile,1,20000,2000,5,Card,18000,2024-01-03,Weekday,With Discount,18000,18000
3,1004,2024-01-04,Sneha,Pune,Groceries,Rice Bag,5,1200,100,3,UPI,5500,2024-01-04,Weekday,With Discount,1100,5500
4,1005,2024-01-05,Vikram,Bangalore,Clothing,Jeans,2,1500,0,4,Card,3000,2024-01-05,Weekday,No Discount,1500,3000
5,1006,2024-01-06,Amit,Pune,Electronics,Headphones,2,2500,200,4,UPI,4600,2024-01-06,Weekend,With Discount,2300,4600
6,1007,2024-01-07,Neha,Mumbai,Groceries,Oil,3,900,50,3,COD,2550,2024-01-07,Weekend,With Discount,850,2550
7,1008,2024-01-08,Rohit,Delhi,Clothing,Shirt,2,1000,0,4,Card,2000,2024-01-08,Weekday,No Discount,1000,2000
8,1009,2024-01-09,Pooja,Pune,Electronics,Tablet,1,15000,1500,5,UPI,13500,2024-01-09,Weekday,With Discount,13500,13500
9,1010,2024-01-10,Amit,Pune,Groceries,Milk,4,600,0,3,UPI,2400,2024-01-10,Weekday,No Discount,600,2400
10,1011,2024-01-11,Riya,Mumbai,Clothing,Jacket,1,2200,100,4,Card,2100,2024-01-11,Weekday,With Discount,2100,2100
11,1012,2024-01-12,Rahul,Delhi,Electronics,Camera,1,30000,3000,5,Card,27000,2024-01-12,Weekday,With Discount,27000,27000
12,1013,2024-01-13,Sneha,Pune,Groceries,Wheat,6,1800,200,3,COD,9600,2024-01-13,Weekend,With Discount,1600,9600
13,1014,2024-01-14,Vikram,Bangalore,Clothing,Trousers,2,1700,0,4,UPI,3400,2024-01-14,Weekend,No Discount,1700,3400
14,1015,2024-01-15,Amit,Pune,Electronics,Speaker,1,4000,500,5,UPI,3500,2024-01-15,Weekday,With Discount,3500,3500
15,1016,2024-01-16,Rohit,Delhi,Groceries,Sugar,3,700,0,3,COD,2100,2024-01-16,Weekday,No Discount,700,2100
16,1017,2024-01-17,Pooja,Pune,Electronics,Smartwatch,1,8000,1000,5,Card,7000,2024-01-17,Weekday,With Discount,7000,7000
17,1018,2024-01-18,Neha,Mumbai,Clothing,Dress,2,1400,100,4,UPI,2600,2024-01-18,Weekday,With Discount,1300,2600
18,1019,2024-01-19,Riya,Mumbai,Electronics,Powerbank,2,1200,0,4,Card,2400,2024-01-19,Weekday,No Discount,1200,2400
19,1020,2024-01-20,Rahul,Delhi,Groceries,Tea,5,500,50,3,COD,2250,2024-01-20,Weekend,With Discount,450,2250

In [39]:
### Q29. Find top 3 highest value orders
top_orders = df.sort_values(by="TotalValue", ascending=False).head(3)
print(top_orders)

    OrderID  OrderDate Customer   City     Category Product  Quantity  Price  \
0      1001 2024-01-01     Amit   Pune  Electronics  Laptop         1  55000
11     1012 2024-01-12    Rahul  Delhi  Electronics  Camera         1  30000
2      1003 2024-01-03    Rahul  Delhi  Electronics  Mobile         1  20000

    Discount  Rating PaymentMethod  NetAmount       Date  DayType  \
0       5000       5           UPI      50000 2024-01-01  Weekday
11      3000       5          Card      27000 2024-01-12  Weekday
2       2000       5          Card      18000 2024-01-03  Weekday

     DiscountFlag  NetPrice  TotalValue
0   With Discount     50000       50000
11  With Discount     27000       27000
2   With Discount     18000       18000

In [44]:
high_discount = df[df["Discount"] > 0.20]
df

,OrderID,OrderDate,Customer,City,Category,Product,Quantity,Price,Discount,Rating,PaymentMethod,NetAmount,Date,DayType,DiscountFlag,NetPrice,TotalValue
0,1001,2024-01-01,Amit,Pune,Electronics,Laptop,1,55000,5000,5,UPI,50000,2024-01-01,Weekday,With Discount,50000,50000
1,1002,2024-01-02,Neha,Mumbai,Clothing,T-Shirt,3,800,0,4,COD,2400,2024-01-02,Weekday,No Discount,800,2400
2,1003,2024-01-03,Rahul,Delhi,Electronics,Mobile,1,20000,2000,5,Card,18000,2024-01-03,Weekday,With Discount,18000,18000
3,1004,2024-01-04,Sneha,Pune,Groceries,Rice Bag,5,1200,100,3,UPI,5500,2024-01-04,Weekday,With Discount,1100,5500
4,1005,2024-01-05,Vikram,Bangalore,Clothing,Jeans,2,1500,0,4,Card,3000,2024-01-05,Weekday,No Discount,1500,3000
5,1006,2024-01-06,Amit,Pune,Electronics,Headphones,2,2500,200,4,UPI,4600,2024-01-06,Weekend,With Discount,2300,4600
6,1007,2024-01-07,Neha,Mumbai,Groceries,Oil,3,900,50,3,COD,2550,2024-01-07,Weekend,With Discount,850,2550
7,1008,2024-01-08,Rohit,Delhi,Clothing,Shirt,2,1000,0,4,Card,2000,2024-01-08,Weekday,No Discount,1000,2000
8,1009,2024-01-09,Pooja,Pune,Electronics,Tablet,1,15000,1500,5,UPI,13500,2024-01-09,Weekday,With Discount,13500,13500
9,1010,2024-01-10,Amit,Pune,Groceries,Milk,4,600,0,3,UPI,2400,2024-01-10,Weekday,No Discount,600,2400
10,1011,2024-01-11,Riya,Mumbai,Clothing,Jacket,1,2200,100,4,Card,2100,2024-01-11,Weekday,With Discount,2100,2100
11,1012,2024-01-12,Rahul,Delhi,Electronics,Camera,1,30000,3000,5,Card,27000,2024-01-12,Weekday,With Discount,27000,27000
12,1013,2024-01-13,Sneha,Pune,Groceries,Wheat,6,1800,200,3,COD,9600,2024-01-13,Weekend,With Discount,1600,9600
13,1014,2024-01-14,Vikram,Bangalore,Clothing,Trousers,2,1700,0,4,UPI,3400,2024-01-14,Weekend,No Discount,1700,3400
14,1015,2024-01-15,Amit,Pune,Electronics,Speaker,1,4000,500,5,UPI,3500,2024-01-15,Weekday,With Discount,3500,3500
15,1016,2024-01-16,Rohit,Delhi,Groceries,Sugar,3,700,0,3,COD,2100,2024-01-16,Weekday,No Discount,700,2100
16,1017,2024-01-17,Pooja,Pune,Electronics,Smartwatch,1,8000,1000,5,Card,7000,2024-01-17,Weekday,With Discount,7000,7000
17,1018,2024-01-18,Neha,Mumbai,Clothing,Dress,2,1400,100,4,UPI,2600,2024-01-18,Weekday,With Discount,1300,2600
18,1019,2024-01-19,Riya,Mumbai,Electronics,Powerbank,2,1200,0,4,Card,2400,2024-01-19,Weekday,No Discount,1200,2400
19,1020,2024-01-20,Rahul,Delhi,Groceries,Tea,5,500,50,3,COD,2250,2024-01-20,Weekend,With Discount,450,2250

In [45]:
### Q32. Find duplicate customers with multiple cities
duplicate_customers = df.groupby("Customer")["City"].nunique()
duplicate_customers = duplicate_customers[duplicate_customers > 1]

print(duplicate_customers)

Series([], Name: City, dtype: int64)

Great idea 👍 — doing **case studies** is the fastest way to master **pandas**.

Below is a **complete real-world style dataset + practice questions** that will take you from intermediate → advanced level.

---

# 🧠 Pandas Case Study: Online Retail Orders

## ✅ Step 1: Create Dataset

Copy & run:

```python
import pandas as pd

data = {
    "OrderID": range(1001, 1021),
    "OrderDate": [
        "2024-01-01","2024-01-02","2024-01-03","2024-01-04","2024-01-05",
        "2024-01-06","2024-01-07","2024-01-08","2024-01-09","2024-01-10",
        "2024-01-11","2024-01-12","2024-01-13","2024-01-14","2024-01-15",
        "2024-01-16","2024-01-17","2024-01-18","2024-01-19","2024-01-20"
    ],
    "Customer": ["Amit","Neha","Rahul","Sneha","Vikram","Amit","Neha","Rohit","Pooja","Amit",
                 "Riya","Rahul","Sneha","Vikram","Amit","Rohit","Pooja","Neha","Riya","Rahul"],
    "City": ["Pune","Mumbai","Delhi","Pune","Bangalore","Pune","Mumbai","Delhi","Pune","Pune",
             "Mumbai","Delhi","Pune","Bangalore","Pune","Delhi","Pune","Mumbai","Mumbai","Delhi"],
    "Category": ["Electronics","Clothing","Electronics","Groceries","Clothing","Electronics",
                 "Groceries","Clothing","Electronics","Groceries","Clothing","Electronics",
                 "Groceries","Clothing","Electronics","Groceries","Electronics","Clothing",
                 "Electronics","Groceries"],
    "Product": ["Laptop","T-Shirt","Mobile","Rice Bag","Jeans","Headphones","Oil","Shirt",
                "Tablet","Milk","Jacket","Camera","Wheat","Trousers","Speaker","Sugar",
                "Smartwatch","Dress","Powerbank","Tea"],
    "Quantity": [1,3,1,5,2,2,3,2,1,4,1,1,6,2,1,3,1,2,2,5],
    "Price": [55000,800,20000,1200,1500,2500,900,1000,15000,600,2200,30000,1800,1700,4000,700,8000,1400,1200,500],
    "Discount": [5000,0,2000,100,0,200,50,0,1500,0,100,3000,200,0,500,0,1000,100,0,50],
    "Rating": [5,4,5,3,4,4,3,4,5,3,4,5,3,4,5,3,5,4,4,3],
    "PaymentMethod": ["UPI","COD","Card","UPI","Card","UPI","COD","Card","UPI","UPI",
                      "Card","Card","COD","UPI","UPI","COD","Card","UPI","Card","COD"]
}

df = pd.DataFrame(data)
df["OrderDate"] = pd.to_datetime(df["OrderDate"])

df.head()
```

---

# 🎯 SECTION 1 — Basic Exploration

### Q1. Total number of orders

### Q2. Total revenue (before discount)

### Q3. Total discount given

### Q4. Net revenue after discount

### Q5. Average order value

---

# 🎯 SECTION 2 — Customer Insights

### Q6. Top 5 customers by spending

### Q7. Customer who placed most orders

### Q8. Average rating per customer

### Q9. Customer lifetime value (CLV)

---

# 🎯 SECTION 3 — City Analysis

### Q10. Orders per city

### Q11. Revenue per city

### Q12. Most profitable city

### Q13. City with highest average order value

---

# 🎯 SECTION 4 — Product & Category Insights

### Q14. Most popular category

### Q15. Category generating highest revenue

### Q16. Most ordered product

### Q17. Highest revenue product

### Q18. Average rating by category

---

# 🎯 SECTION 5 — Time Analysis

### Q19. Orders per day

### Q20. Day with highest sales

### Q21. Weekend vs weekday revenue

### Q22. Rolling 3-day average sales

---

# 🎯 SECTION 6 — Discount Analysis

### Q23. Orders with discount vs without

### Q24. Does discount increase quantity ordered?

### Q25. Avg discount per category

### Q26. Discount impact on ratings

---

# 🎯 SECTION 7 — Advanced Pandas Skills

### Q27. Create column: `NetPrice = Price - Discount`

### Q28. Create column: `TotalValue = Quantity * NetPrice`

### Q29. Find top 3 highest value orders

### Q30. Find products where discount > 20%

### Q31. Rank customers by spending

### Q32. Find duplicate customers with multiple cities

---

# 🎯 SECTION 8 — Business Decision Questions (REAL WORLD)

### Q33. Which category should be promoted?

### Q34. Should discounts be increased or reduced?

### Q35. Which city needs marketing focus?

### Q36. Which products should be bundled?

### Q37. Which customers are VIP?

### Q38. Which category has high rating but low sales?

---

# ⭐ BONUS CHALLENGES (MASTER LEVEL)

### 🔥 Q39. Build a pivot table: city vs category revenue

### 🔥 Q40. Find correlation between rating & discount

### 🔥 Q41. Identify outlier orders using IQR

### 🔥 Q42. Cohort-style repeat customer analysis

### 🔥 Q43. Contribution % of each category

### 🔥 Q44. Pareto analysis (top 20% products generating revenue)

---

# 🧠 What You Will Master

✅ filtering & boolean logic
✅ groupby & aggregation
✅ sorting & ranking
✅ feature engineering
✅ pivot tables
✅ business analytics thinking
✅ real-world decision making

---

## If you want, I can next:

✅ give **solutions step-by-step**
✅ provide **advanced Level 2 case study**
✅ create **SQL version of same case**
✅ add **visualization tasks**
✅ give **interview questions from this dataset**

Just tell me 👍