🧾 Case Study 1: E-commerce Orders Dataset

Data columns:
order_id, customer_id, order_date, product, category, price, quantity, city, payment_type, returned

Questions

Convert order_date to datetime and extract month & weekday.

Find total revenue generated.

Identify the top 5 selling products by quantity.

Which category generates the highest revenue?

Find customers who made more than 5 purchases.

Calculate return rate per category.

Which city has the highest average order value?

Detect duplicate orders.

Find orders placed on weekends.

Create a pivot table showing revenue by city vs category.

👉 Concepts: filtering, groupby, aggregation, pivot_table, datetime

🏥 Case Study 2: Hospital Patient Records

Columns:
patient_id, age, gender, diagnosis, admission_date, discharge_date, bill_amount, insurance

Questions

Calculate hospital stay duration.

Find average stay duration per diagnosis.

Which diagnosis generates highest revenue?

Find patients with stay > 10 days.

Percentage of insured vs non-insured patients.

Detect missing discharge dates and handle them.

Find gender-wise average bill.

Create age groups (0–18, 19–40, 41–60, 60+).

👉 Concepts: missing values, feature engineering, apply, binning

📈 Case Study 3: Stock Market Time Series

Columns:
date, company, open, close, high, low, volume

Questions

Calculate daily return percentage.

Find highest closing price per company.

Compute 7-day moving average.

Identify days with abnormal price jumps (>5%).

Resample data to monthly average closing price.

Plot trend of one company.

👉 Concepts: time series, rolling, resampling, indexing

🚕 Case Study 4: Ride Sharing Trips (like Uber/Ola)

Columns:
trip_id, driver_id, pickup_time, drop_time, distance_km, fare, payment_mode, city

Questions

Calculate trip duration.

Compute fare per km.

Find peak hours.

Identify top earning drivers.

Compare cash vs digital payments share.

Detect suspicious trips (distance < 1 km but fare high).

Average trip distance per city.

👉 Concepts: datetime, feature creation, filtering, aggregation

🏫 Case Study 5: Student Performance Data

Columns:
student_id, school, gender, math_score, reading_score, writing_score, attendance, parent_education

Questions

Calculate average score per student.

Find top-performing schools.

Compare performance by gender.

Does attendance correlate with scores?

Identify students at risk (avg < 40).

Create grade column (A/B/C/D).

Find subject with lowest average score.

👉 Concepts: apply, correlation, sorting, conditional columns

In [1]:
import pandas as pd
import numpy as np

np.random.seed(42)

# possible values
products = ["Laptop", "Phone", "Headphones", "Shoes", "Watch",
            "Backpack", "T-shirt", "Keyboard", "Mouse", "Tablet"]

categories = {
    "Laptop": "Electronics",
    "Phone": "Electronics",
    "Headphones": "Electronics",
    "Tablet": "Electronics",
    "Keyboard": "Electronics",
    "Mouse": "Electronics",
    "Shoes": "Fashion",
    "Watch": "Fashion",
    "Backpack": "Accessories",
    "T-shirt": "Fashion"
}

cities = ["Pune", "Mumbai", "Delhi", "Bangalore", "Hyderabad", "Chennai"]
payment_types = ["UPI", "Credit Card", "Debit Card", "Cash on Delivery"]

n = 120

data = {
    "order_id": np.arange(1001, 1001+n),
    "customer_id": np.random.randint(200, 260, n),
    "order_date": pd.to_datetime("2025-01-01") + pd.to_timedelta(np.random.randint(0, 90, n), unit="D"),
    "product": np.random.choice(products, n),
    "price": np.random.randint(500, 60000, n),
    "quantity": np.random.randint(1, 5, n),
    "city": np.random.choice(cities, n),
    "payment_type": np.random.choice(payment_types, n),
    "returned": np.random.choice([True, False], n, p=[0.1, 0.9])
}

df = pd.DataFrame(data)

# map categories
df["category"] = df["product"].map(categories)

# reorder columns
df = df[[
    "order_id", "customer_id", "order_date", "product",
    "category", "price", "quantity", "city",
    "payment_type", "returned"
]]

df.head()

,order_id,customer_id,order_date,product,category,price,quantity,city,payment_type,returned
0,1001,238,2025-01-15,T-shirt,Fashion,50836,3,Mumbai,Credit Card,False
1,1002,251,2025-02-14,Shoes,Fashion,52979,1,Hyderabad,Debit Card,False
2,1003,228,2025-03-06,T-shirt,Fashion,20278,4,Mumbai,Debit Card,False
3,1004,214,2025-03-30,Keyboard,Electronics,57971,1,Mumbai,Credit Card,True
4,1005,242,2025-03-12,Laptop,Electronics,27141,1,Mumbai,Credit Card,True

#### 👉 Concepts: filtering, groupby, aggregation, pivot_table, datetime

#### Questions

In [2]:
#Convert order_date to datetime and extract month & weekday.
#df["order_date"] = pd.to_datetime(df["order_date"])
#df["Month"]=df["order_date"].dt.month
#df["weekday"]=df["order_date"].dt.weekday

#df["Month"] = df["order_date"].dt.month_name()
#df["weekday"] = df["order_date"].dt.day_name()
df.head()

,order_id,customer_id,order_date,product,category,price,quantity,city,payment_type,returned
0,1001,238,2025-01-15,T-shirt,Fashion,50836,3,Mumbai,Credit Card,False
1,1002,251,2025-02-14,Shoes,Fashion,52979,1,Hyderabad,Debit Card,False
2,1003,228,2025-03-06,T-shirt,Fashion,20278,4,Mumbai,Debit Card,False
3,1004,214,2025-03-30,Keyboard,Electronics,57971,1,Mumbai,Credit Card,True
4,1005,242,2025-03-12,Laptop,Electronics,27141,1,Mumbai,Credit Card,True

In [9]:
#find total revenue generated.
df["TotalRevenue"]=df["price"] * df["quantity"].sum()
df.head()

,order_id,customer_id,order_date,product,category,price,quantity,city,payment_type,returned,TotalRevenue
0,1001,238,2025-01-15,T-shirt,Fashion,50836,3,Mumbai,Credit Card,False,14945784
1,1002,251,2025-02-14,Shoes,Fashion,52979,1,Hyderabad,Debit Card,False,15575826
2,1003,228,2025-03-06,T-shirt,Fashion,20278,4,Mumbai,Debit Card,False,5961732
3,1004,214,2025-03-30,Keyboard,Electronics,57971,1,Mumbai,Credit Card,True,17043474
4,1005,242,2025-03-12,Laptop,Electronics,27141,1,Mumbai,Credit Card,True,7979454

In [10]:
#dentify the top 5 selling products by quantity.

df.groupby("product")["quantity"].sum().sort_values(ascending=False).head(5)

product
Headphones    46
Laptop        45
Shoes         34
T-shirt       31
Mouse         29
Name: quantity, dtype: int32

In [42]:
top_products = (
    df.groupby("product", as_index=False)["quantity"]
      .sum()
      .sort_values(by="quantity", ascending=False)
      .head(5)
)

print(top_products)

      product  quantity
1  Headphones        46
3      Laptop        45
6       Shoes        34
7     T-shirt        31
4       Mouse        29

In [11]:
#Which category generates the highest revenue?
df.groupby("category")["TotalRevenue"].sum().sort_values(ascending=True)

category
Accessories    126299754
Fashion        321162072
Electronics    628585230
Name: TotalRevenue, dtype: int32

In [12]:
#Find customers who made more than 5 purchases.
#df.groupby("customer_id")["order_id"].count().sort_values(ascending=False).head(5)    
#✔ shows top 5 buyers
#❌ may include customers with ≤ 5 orders
#❌ misses other customers with >5 orders

order_counts = df.groupby("customer_id")["order_id"].count()

customers_gt5 = order_counts[order_counts > 5]

print(customers_gt5)

customer_id
259    8
Name: order_id, dtype: int64

In [13]:
df

,order_id,customer_id,order_date,product,category,price,quantity,city,payment_type,returned,TotalRevenue
0,1001,238,2025-01-15,T-shirt,Fashion,50836,3,Mumbai,Credit Card,False,14945784
1,1002,251,2025-02-14,Shoes,Fashion,52979,1,Hyderabad,Debit Card,False,15575826
2,1003,228,2025-03-06,T-shirt,Fashion,20278,4,Mumbai,Debit Card,False,5961732
3,1004,214,2025-03-30,Keyboard,Electronics,57971,1,Mumbai,Credit Card,True,17043474
4,1005,242,2025-03-12,Laptop,Electronics,27141,1,Mumbai,Credit Card,True,7979454
...,...,...,...,...,...,...,...,...,...,...,...
115,1116,259,2025-02-22,Headphones,Electronics,25816,3,Chennai,Debit Card,False,7589904
116,1117,259,2025-02-13,Laptop,Electronics,32717,2,Bangalore,Cash on Delivery,False,9618798
117,1118,244,2025-03-31,Shoes,Fashion,8808,3,Delhi,UPI,True,2589552
118,1119,240,2025-02-01,Watch,Fashion,6449,3,Hyderabad,Debit Card,False,1896006
119,1120,228,2025-03-11,T-shirt,Fashion,52490,1,Bangalore,UPI,False,15432060

In [59]:
#Calculate return rate per category.
#df.groupby("category")["returned"].mean()
#
df.groupby("category")["returned"].mean() * 100

category
Accessories     7.692308
Electronics    11.267606
Fashion         8.333333
Name: returned, dtype: float64

In [14]:
#Which city has the highest average order value?

df["order_value"] = df["price"] * df["quantity"]
df.groupby("city")["order_value"].mean().sort_values(ascending=False)

city
Chennai      108367.166667
Pune          83036.478261
Mumbai        81990.500000
Delhi         68229.647059
Hyderabad     66113.814815
Bangalore     59824.952381
Name: order_value, dtype: float64

In [16]:
#Detect duplicate orders.
#✅ 1️⃣ Check if duplicates exist
df.duplicated().sum()
#✅ 2️⃣ View duplicate rows
#df[df.duplicated()]
#✅ 4️⃣ Check duplicates based on order_id (most common)
df[df.duplicated(subset="order_id", keep=False)]
#✅ 5️⃣ Count duplicate order IDs
df["order_id"].duplicated().sum()
#✅ 6️⃣ Remove duplicates
df = df.drop_duplicates()

In [17]:
#Find orders placed on weekends.
df[df["order_date"].dt.day_name().isin(["Saturday", "Sunday"])]

,order_id,customer_id,order_date,product,category,price,quantity,city,payment_type,returned,TotalRevenue,order_value
3,1004,214,2025-03-30,Keyboard,Electronics,57971,1,Mumbai,Credit Card,True,17043474,57971
6,1007,220,2025-03-29,Keyboard,Electronics,33245,2,Mumbai,Debit Card,False,9774030,66490
9,1010,218,2025-03-29,Phone,Electronics,1069,2,Bangalore,UPI,False,314286,2138
11,1012,210,2025-01-11,Backpack,Accessories,35163,2,Hyderabad,Credit Card,False,10337922,70326
12,1013,210,2025-03-22,Laptop,Electronics,52385,2,Mumbai,Cash on Delivery,False,15401190,104770
16,1017,239,2025-02-02,Shoes,Fashion,4514,1,Bangalore,Cash on Delivery,False,1327116,4514
17,1018,223,2025-01-05,Shoes,Fashion,11593,1,Pune,Cash on Delivery,True,3408342,11593
23,1024,243,2025-01-12,T-shirt,Fashion,34677,3,Hyderabad,Debit Card,False,10195038,104031
25,1026,237,2025-02-02,Mouse,Electronics,1284,2,Delhi,Cash on Delivery,False,377496,2568
29,1030,232,2025-03-29,Phone,Electronics,13033,4,Mumbai,Cash on Delivery,False,3831702,52132
35,1036,248,2025-02-16,T-shirt,Fashion,50189,1,Hyderabad,UPI,False,14755566,50189
39,1040,227,2025-01-05,Tablet,Electronics,11147,1,Chennai,UPI,False,3277218,11147
52,1053,206,2025-01-04,Headphones,Electronics,11393,1,Hyderabad,Debit Card,True,3349542,11393
59,1060,259,2025-02-01,Shoes,Fashion,13621,3,Bangalore,UPI,False,4004574,40863
76,1077,213,2025-03-16,Shoes,Fashion,53506,1,Mumbai,Cash on Delivery,False,15730764,53506
77,1078,216,2025-03-30,Laptop,Electronics,30249,4,Chennai,Credit Card,False,8893206,120996
95,1096,213,2025-02-01,Backpack,Accessories,4642,1,Mumbai,Cash on Delivery,False,1364748,4642
96,1097,230,2025-03-29,Keyboard,Electronics,15702,1,Pune,Cash on Delivery,False,4616388,15702
101,1102,222,2025-01-12,Watch,Fashion,29440,3,Hyderabad,UPI,False,8655360,88320
102,1103,259,2025-02-08,Headphones,Electronics,37733,1,Hyderabad,UPI,True,11093502,37733
106,1107,215,2025-03-22,Laptop,Electronics,26758,3,Hyderabad,Cash on Delivery,False,7866852,80274
110,1111,252,2025-02-23,Mouse,Electronics,14598,4,Pune,Credit Card,False,4291812,58392
113,1114,224,2025-01-19,Laptop,Electronics,47530,2,Bangalore,Credit Card,False,13973820,95060
115,1116,259,2025-02-22,Headphones,Electronics,25816,3,Chennai,Debit Card,False,7589904,77448
118,1119,240,2025-02-01,Watch,Fashion,6449,3,Hyderabad,Debit Card,False,1896006,19347

In [70]:
#Create a pivot table showing revenue by city vs category.
pd.pivot_table(
    df,
    values="order_value",
    index="city",
    columns="category",
    aggfunc="sum",
    fill_value=0
)

category   Accessories  Electronics  Fashion
city
Bangalore       145062       806842   304420
Chennai         482200       635842   182364
Delhi            46181       886640   227083
Hyderabad       138723      1043245   603105
Mumbai          159482       863562   616766
Pune                 0      1168705   741134