## PANDAS BY CHATGPT

## We’ll cover:

✅ Creating DataFrames in different ways
✅ Viewing & understanding data
✅ Selecting & filtering data
✅ Data manipulation formulas
✅ Cleaning & transforming data
✅ Grouping & aggregation
✅ Real practice tasks

## 🐼 Lesson 1: What is Pandas?

Pandas is a Python library used for:

✔ handling tables (like Excel)
✔ cleaning messy data
✔ analyzing & summarizing data
✔ working with CSV/Excel files

In [ ]:
#Install (if needed)
pip install pandas

#Import Pandas
import pandas as pd

### 🐼 Lesson 2: Creating DataFrames (Multiple Ways)
### ✅ Method 1: From Dictionary (MOST COMMON)

In [1]:
import pandas as pd

data = {
    "Name": ["Amit", "Sara", "Raj"],
    "Age": [25, 30, 22],
    "City": ["Pune", "Mumbai", "Delhi"]
}

df = pd.DataFrame(data)
print(df)

   Name  Age    City
0  Amit   25    Pune
1  Sara   30  Mumbai
2   Raj   22   Delhi

### ✅ Method 2: From List of Lists

In [4]:

data = [
    ["Amit", 25, "Pune"],
    ["Sara", 30, "Mumbai"],
    ["Raj", 22, "Delhi"]
]

df = pd.DataFrame(data, columns=["Name", "Age", "City"])
df

   Name  Age    City
0  Amit   25    Pune
1  Sara   30  Mumbai
2   Raj   22   Delhi

### ✅ Method 3: From List of Dictionaries

In [5]:
data = [
    {"Name": "Amit", "Age": 25},
    {"Name": "Sara", "Age": 30}
]

df = pd.DataFrame(data)
df

   Name  Age
0  Amit   25
1  Sara   30

### ✅ Method 4: From NumPy Array

In [7]:
import numpy as np

arr = np.array([[1,2], [3,4]])
df = pd.DataFrame(arr, columns=["A", "B"])

### ✅ Method 5: From CSV File

In [ ]:
df = pd.read_csv("data.csv")

🧪 PRACTICE TASK 1

Create a DataFrame using dictionary:

Product	Price	Quantity
Pen	10	50
Book	120	20
Pencil	5	100

👉 Try yourself before continuing.

In [10]:
data={
"product":["pen","book","pencil"],
    "price": [10,120,5],
    "pencil": [50,20,100]
}

df=pd.DataFrame(data)
df

  product  price  pencil
0     pen     10      50
1    book    120      20
2  pencil      5     100

### 🐼 Lesson 3: Viewing & Understanding Data

Assume:

df = pd.read_csv("data.csv")

In [77]:
df=pd.read_csv("C:\python\employees.csv")
df

      Name  Age       City  Salary
0     Amit   25       Pune   25000
1     Sara   30     Mumbai   30000
2      Raj   22      Delhi   22000
3     Neha   28  Bangalore   28000
4   Vikram   35  Hyderabad   35000
5     Amit   25       Pune   25000
6     Sara   30     Mumbai   30000
7      Raj   22      Delhi   22000
8     Neha   28  Bangalore   28000
9   Vikram   35  Hyderabad   35000
10    Amit   25       Pune   25000
11    Sara   30     Mumbai   30000
12     Raj   22      Delhi   22000
13    Neha   28  Bangalore   28000
14  Vikram   35  Hyderabad   35000
15    Amit   25       Pune   25000
16    Sara   30     Mumbai   30000
17     Raj   22      Delhi   22000
18    Neha   28  Bangalore   28000
19  Vikram   35  Hyderabad   35000

### Viewing & Understanding Data

In [41]:
#View first rows
df.head()

     Name  Age       City  Salary
0    Amit   25       Pune   25000
1    Sara   30     Mumbai   30000
2     Raj   22      Delhi   22000
3    Neha   28  Bangalore   28000
4  Vikram   35  Hyderabad   35000

In [42]:
#View last rows
df.tail()

      Name  Age       City  Salary
15    Amit   25       Pune   25000
16    Sara   30     Mumbai   30000
17     Raj   22      Delhi   22000
18    Neha   28  Bangalore   28000
19  Vikram   35  Hyderabad   35000

In [43]:
#Info about data
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    20 non-null     object
 1   Age     20 non-null     int64
 2   City    20 non-null     object
 3   Salary  20 non-null     int64
dtypes: int64(2), object(2)
memory usage: 772.0+ bytes

In [44]:
#Statistics summary
df.describe()

           Age        Salary
count  20.0000     20.000000
mean   28.0000  28000.000000
std     4.5422   4542.199792
min    22.0000  22000.000000
25%    25.0000  25000.000000
50%    28.0000  28000.000000
75%    30.0000  30000.000000
max    35.0000  35000.000000

### 🐼 Lesson 4: Selecting Data

In [45]:
#Select one column
df["Name"]

0       Amit
1       Sara
2        Raj
3       Neha
4     Vikram
5       Amit
6       Sara
7        Raj
8       Neha
9     Vikram
10      Amit
11      Sara
12       Raj
13      Neha
14    Vikram
15      Amit
16      Sara
17       Raj
18      Neha
19    Vikram
Name: Name, dtype: object

In [46]:
#Select multiple columns
df[["Name", "Age"]]

      Name  Age
0     Amit   25
1     Sara   30
2      Raj   22
3     Neha   28
4   Vikram   35
5     Amit   25
6     Sara   30
7      Raj   22
8     Neha   28
9   Vikram   35
10    Amit   25
11    Sara   30
12     Raj   22
13    Neha   28
14  Vikram   35
15    Amit   25
16    Sara   30
17     Raj   22
18    Neha   28
19  Vikram   35

In [47]:
#Select rows by index
df.loc[0]

Name       Amit
Age          25
City       Pune
Salary    25000
Name: 0, dtype: object

In [48]:
#Select rows & columns
df.loc[0, "Name"]

'Amit'

In [49]:
#🔹 Step 1: Check Data Types

print(df.dtypes)

Name      object
Age        int64
City      object
Salary     int64
dtype: object

### 🔹 Convert numeric columns

In [50]:
#df["Age"] = pd.to_numeric(df["Age"])
#df["Salary"] = pd.to_numeric(df["Salary"])

### 🐼 Lesson 5: Filtering Data

In [51]:
#Example Data
df[df["Age"] > 25]

      Name  Age       City  Salary
1     Sara   30     Mumbai   30000
3     Neha   28  Bangalore   28000
4   Vikram   35  Hyderabad   35000
6     Sara   30     Mumbai   30000
8     Neha   28  Bangalore   28000
9   Vikram   35  Hyderabad   35000
11    Sara   30     Mumbai   30000
13    Neha   28  Bangalore   28000
14  Vikram   35  Hyderabad   35000
16    Sara   30     Mumbai   30000
18    Neha   28  Bangalore   28000
19  Vikram   35  Hyderabad   35000

In [52]:
#Multiple Conditions
df[(df["Age"] > 20) & (df["City"] == "Pune")]

    Name  Age  City  Salary
0   Amit   25  Pune   25000
5   Amit   25  Pune   25000
10  Amit   25  Pune   25000
15  Amit   25  Pune   25000

### 🧪 PRACTICE TASK 2

Filter rows where:

✔ Age > 23
✔ City = Pune

In [53]:
df[(df["Age"]>20) & (df["City"]=="Pune")]

    Name  Age  City  Salary
0   Amit   25  Pune   25000
5   Amit   25  Pune   25000
10  Amit   25  Pune   25000
15  Amit   25  Pune   25000

### 🐼 Lesson 6: Adding & Modifying Columns

In [58]:
# Add new column
df["index"] = [1, 2, 3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20]
df

      Name  Age       City  Salary  index
0     Amit   25       Pune   25000      1
1     Sara   30     Mumbai   30000      2
2      Raj   22      Delhi   22000      3
3     Neha   28  Bangalore   28000      4
4   Vikram   35  Hyderabad   35000      5
5     Amit   25       Pune   25000      6
6     Sara   30     Mumbai   30000      7
7      Raj   22      Delhi   22000      8
8     Neha   28  Bangalore   28000      9
9   Vikram   35  Hyderabad   35000     10
10    Amit   25       Pune   25000     11
11    Sara   30     Mumbai   30000     12
12     Raj   22      Delhi   22000     13
13    Neha   28  Bangalore   28000     14
14  Vikram   35  Hyderabad   35000     15
15    Amit   25       Pune   25000     16
16    Sara   30     Mumbai   30000     17
17     Raj   22      Delhi   22000     18
18    Neha   28  Bangalore   28000     19
19  Vikram   35  Hyderabad   35000     20

In [60]:
# Create column from formula
df["Bonus"] = df["Salary"] * 0.10
df

      Name  Age       City  Salary  index   Bonus
0     Amit   25       Pune   25000      1  2500.0
1     Sara   30     Mumbai   30000      2  3000.0
2      Raj   22      Delhi   22000      3  2200.0
3     Neha   28  Bangalore   28000      4  2800.0
4   Vikram   35  Hyderabad   35000      5  3500.0
5     Amit   25       Pune   25000      6  2500.0
6     Sara   30     Mumbai   30000      7  3000.0
7      Raj   22      Delhi   22000      8  2200.0
8     Neha   28  Bangalore   28000      9  2800.0
9   Vikram   35  Hyderabad   35000     10  3500.0
10    Amit   25       Pune   25000     11  2500.0
11    Sara   30     Mumbai   30000     12  3000.0
12     Raj   22      Delhi   22000     13  2200.0
13    Neha   28  Bangalore   28000     14  2800.0
14  Vikram   35  Hyderabad   35000     15  3500.0
15    Amit   25       Pune   25000     16  2500.0
16    Sara   30     Mumbai   30000     17  3000.0
17     Raj   22      Delhi   22000     18  2200.0
18    Neha   28  Bangalore   28000     19  2800.0
19  Vikram   35  Hyderabad   35000     20  3500.0

In [62]:
#Modify values
df["Age"] = df["Age"] + 1
df

      Name  Age       City  Salary  index   Bonus
0     Amit   27       Pune   25000      1  2500.0
1     Sara   32     Mumbai   30000      2  3000.0
2      Raj   24      Delhi   22000      3  2200.0
3     Neha   30  Bangalore   28000      4  2800.0
4   Vikram   37  Hyderabad   35000      5  3500.0
5     Amit   27       Pune   25000      6  2500.0
6     Sara   32     Mumbai   30000      7  3000.0
7      Raj   24      Delhi   22000      8  2200.0
8     Neha   30  Bangalore   28000      9  2800.0
9   Vikram   37  Hyderabad   35000     10  3500.0
10    Amit   27       Pune   25000     11  2500.0
11    Sara   32     Mumbai   30000     12  3000.0
12     Raj   24      Delhi   22000     13  2200.0
13    Neha   30  Bangalore   28000     14  2800.0
14  Vikram   37  Hyderabad   35000     15  3500.0
15    Amit   27       Pune   25000     16  2500.0
16    Sara   32     Mumbai   30000     17  3000.0
17     Raj   24      Delhi   22000     18  2200.0
18    Neha   30  Bangalore   28000     19  2800.0
19  Vikram   37  Hyderabad   35000     20  3500.0

### 🐼 Lesson 7: Deleting Columns & Rows

In [ ]:
#Delete column
df.drop("Bonus", axis=1, inplace=True)

In [70]:
df

      Name  Age       City  index
0     Amit   27       Pune      1
1     Sara   32     Mumbai      2
2      Raj   24      Delhi      3
3     Neha   30  Bangalore      4
4   Vikram   37  Hyderabad      5
5     Amit   27       Pune      6
6     Sara   32     Mumbai      7
7      Raj   24      Delhi      8
8     Neha   30  Bangalore      9
9   Vikram   37  Hyderabad     10
10    Amit   27       Pune     11
11    Sara   32     Mumbai     12
12     Raj   24      Delhi     13
13    Neha   30  Bangalore     14
14  Vikram   37  Hyderabad     15
15    Amit   27       Pune     16
16    Sara   32     Mumbai     17
17     Raj   24      Delhi     18
18    Neha   30  Bangalore     19
19  Vikram   37  Hyderabad     20

In [71]:
#Delete row
df.drop(0, inplace=True)
df

      Name  Age       City  index
1     Sara   32     Mumbai      2
2      Raj   24      Delhi      3
3     Neha   30  Bangalore      4
4   Vikram   37  Hyderabad      5
5     Amit   27       Pune      6
6     Sara   32     Mumbai      7
7      Raj   24      Delhi      8
8     Neha   30  Bangalore      9
9   Vikram   37  Hyderabad     10
10    Amit   27       Pune     11
11    Sara   32     Mumbai     12
12     Raj   24      Delhi     13
13    Neha   30  Bangalore     14
14  Vikram   37  Hyderabad     15
15    Amit   27       Pune     16
16    Sara   32     Mumbai     17
17     Raj   24      Delhi     18
18    Neha   30  Bangalore     19
19  Vikram   37  Hyderabad     20

### 🐼 Lesson 8: Handling Missing Data

In [72]:
#Detect missing values
df.isnull()

     Name    Age   City  index
1   False  False  False  False
2   False  False  False  False
3   False  False  False  False
4   False  False  False  False
5   False  False  False  False
6   False  False  False  False
7   False  False  False  False
8   False  False  False  False
9   False  False  False  False
10  False  False  False  False
11  False  False  False  False
12  False  False  False  False
13  False  False  False  False
14  False  False  False  False
15  False  False  False  False
16  False  False  False  False
17  False  False  False  False
18  False  False  False  False
19  False  False  False  False

In [73]:
#Drop missing values
df.dropna()

      Name  Age       City  index
1     Sara   32     Mumbai      2
2      Raj   24      Delhi      3
3     Neha   30  Bangalore      4
4   Vikram   37  Hyderabad      5
5     Amit   27       Pune      6
6     Sara   32     Mumbai      7
7      Raj   24      Delhi      8
8     Neha   30  Bangalore      9
9   Vikram   37  Hyderabad     10
10    Amit   27       Pune     11
11    Sara   32     Mumbai     12
12     Raj   24      Delhi     13
13    Neha   30  Bangalore     14
14  Vikram   37  Hyderabad     15
15    Amit   27       Pune     16
16    Sara   32     Mumbai     17
17     Raj   24      Delhi     18
18    Neha   30  Bangalore     19
19  Vikram   37  Hyderabad     20

In [74]:
#Fill missing values
df.fillna(0)

      Name  Age       City  index
1     Sara   32     Mumbai      2
2      Raj   24      Delhi      3
3     Neha   30  Bangalore      4
4   Vikram   37  Hyderabad      5
5     Amit   27       Pune      6
6     Sara   32     Mumbai      7
7      Raj   24      Delhi      8
8     Neha   30  Bangalore      9
9   Vikram   37  Hyderabad     10
10    Amit   27       Pune     11
11    Sara   32     Mumbai     12
12     Raj   24      Delhi     13
13    Neha   30  Bangalore     14
14  Vikram   37  Hyderabad     15
15    Amit   27       Pune     16
16    Sara   32     Mumbai     17
17     Raj   24      Delhi     18
18    Neha   30  Bangalore     19
19  Vikram   37  Hyderabad     20

### 🐼 Lesson 9: Sorting Data

In [75]:
df.sort_values("Age")

      Name  Age       City  index
2      Raj   24      Delhi      3
17     Raj   24      Delhi     18
7      Raj   24      Delhi      8
12     Raj   24      Delhi     13
10    Amit   27       Pune     11
5     Amit   27       Pune      6
15    Amit   27       Pune     16
3     Neha   30  Bangalore      4
8     Neha   30  Bangalore      9
18    Neha   30  Bangalore     19
13    Neha   30  Bangalore     14
16    Sara   32     Mumbai     17
1     Sara   32     Mumbai      2
6     Sara   32     Mumbai      7
11    Sara   32     Mumbai     12
14  Vikram   37  Hyderabad     15
9   Vikram   37  Hyderabad     10
4   Vikram   37  Hyderabad      5
19  Vikram   37  Hyderabad     20

In [76]:
#Descending:

df.sort_values("Age", ascending=False)

      Name  Age       City  index
19  Vikram   37  Hyderabad     20
9   Vikram   37  Hyderabad     10
4   Vikram   37  Hyderabad      5
14  Vikram   37  Hyderabad     15
16    Sara   32     Mumbai     17
11    Sara   32     Mumbai     12
1     Sara   32     Mumbai      2
6     Sara   32     Mumbai      7
8     Neha   30  Bangalore      9
13    Neha   30  Bangalore     14
3     Neha   30  Bangalore      4
18    Neha   30  Bangalore     19
5     Amit   27       Pune      6
15    Amit   27       Pune     16
10    Amit   27       Pune     11
7      Raj   24      Delhi      8
2      Raj   24      Delhi      3
12     Raj   24      Delhi     13
17     Raj   24      Delhi     18

### 🐼 Lesson 10: Grouping & Aggregation
sum()
max()
min()
count()

In [82]:
#Example

df.groupby("City")["Salary"].mean()

City
Bangalore    28000.0
Delhi        22000.0
Hyderabad    35000.0
Mumbai       30000.0
Pune         25000.0
Name: Salary, dtype: float64

In [83]:
df.groupby("City")["Salary"].max()

City
Bangalore    28000
Delhi        22000
Hyderabad    35000
Mumbai       30000
Pune         25000
Name: Salary, dtype: int64

In [84]:
df.groupby("City")["Salary"].count()

City
Bangalore    4
Delhi        4
Hyderabad    4
Mumbai       4
Pune         4
Name: Salary, dtype: int64

### 🧪 PRACTICE TASK 3

Create DataFrame:

Name	Department	Salary
Amit	IT	40000
Sara	HR	35000
Raj	IT	45000
Neha	HR	30000

In [89]:
data={
"name":["Amit","Sara","Raj","Neha"],
    "Department":["IT","HR","IT","HR"],
    "Salary":[40000,35000,45000,30000]
}
df=pd.DataFrame(data)
df

   name Department  Salary
0  Amit         IT   40000
1  Sara         HR   35000
2   Raj         IT   45000
3  Neha         HR   30000

### 👉 Find:

1️⃣ Average salary per department
2️⃣ Total salary per department

In [90]:
#Average salary per department
df.groupby("Department")["Salary"].mean()

Department
HR    32500.0
IT    42500.0
Name: Salary, dtype: float64

In [91]:
#Total salary per department
df.groupby("Department")["Salary"].sum()

Department
HR    65000
IT    85000
Name: Salary, dtype: int64

### 🐼 Lesson 11: Exporting Data

In [92]:
# df.to_csv("output.csv", index=False)

### 🎯 MINI PROJECT (REAL PRACTICE)


Create student data:

Name	Marks
A	85
B	40
C	72
D	30

Tasks:

✔ Add column Result (Pass if marks > 50)
✔ Find average marks
✔ Show students who failed
✔ Sort by marks